# Copyright (C) 2025 LZX Industries LLC
# SPDX-License-Identifier: GPL-3.0-only
#
# Videomancer Core RevB Hardware Configuration

[hardware]
name = "videomancer_core_revb"
platform = "ice40"
device = "hx4k"
package = "tq144"
